
# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: SRFAppAgentPool

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "Install Angular cli"
  inputs:
    command: "custom"
    customCommand: "install --location=global @angular/cli@16.2.10"

- task: Npm@1
  displayName: "Install npm packages"
  inputs:
    command: "install"
    verbose: true
  
- task: CmdLine@2
  displayName: "Build Angular app"
  inputs:
    script: 'ng build -c=production --base-href=/vms/'

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact: Angular"
  inputs:
    PathtoPublish: "$(Build.SourcesDirectory)/dist"
    FileCopyOptions:
    ArtifactName: "Angular"
    publishLocation: "Container"